ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS 
packed_at TIMESTAMPTZ DEFAULT NULL;

ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS
accepted_at TIMESTAMPTZ DEFAULT NULL;

ALTER TABLE public.shipments
ADD COLUMN IF NOT EXISTS
manifest_printed BOOLEAN DEFAULT false;
